// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SISCO_SAYACv3._5.Models;

namespace SISCO_SAYACv3._5.Migrations
{
    [DbContext(typeof(SISCO_SAYACv3_5Context))]
    [Migration("20190702234342_one")]
    partial class one
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Auditorias", b =>
                {
                    b.Property<int>("AuditoriasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Fecha_Final");

                    b.Property<DateTime>("Fecha_Inicio");

                    b.Property<int>("UsuariosId");

                    b.HasKey("AuditoriasId");

                    b.HasIndex("UsuariosId");

                    b.ToTable("Auditorias");
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Contratistas", b =>
                {
                    b.Property<int>("ContratistasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("correo_electronico")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<int>("numero_identificacion");

                    b.Property<string>("primer_apellido")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("primer_nombre")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("segundo_apellido")
                        .HasMaxLength(60);

                    b.Property<string>("segundo_nombre")
                        .HasMaxLength(60);

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("tipo_documento")
                        .IsRequired();

                    b.HasKey("ContratistasId");

                    b.ToTable("Contratistas");
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Contratos", b =>
                {
                    b.Property<int>("ContratosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratistasId");

                    b.Property<string>("estado")
                        .IsRequired();

                    b.Property<DateTime>("fecha_fin");

                    b.Property<DateTime>("fecha_inicio");

                    b.Property<string>("observaciones")
                        .HasMaxLength(200);

                    b.Property<double>("porcentaje_adicional");

                    b.Property<double>("porcentaje_multa");

                    b.Property<double>("tiempo_desfase");

                    b.Property<double>("valor_contrato");

                    b.HasKey("ContratosId");

                    b.HasIndex("ContratistasId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Obras", b =>
                {
                    b.Property<int>("ObrasId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratistasId");

                    b.Property<int>("ContratosId");

                    b.Property<string>("direccion_obra")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("nombre_obra")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("tipo_obra")
                        .IsRequired();

                    b.HasKey("ObrasId");

                    b.HasIndex("ContratistasId");

                    b.HasIndex("ContratosId")
                        .IsUnique();

                    b.ToTable("Obras");
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Reportes", b =>
                {
                    b.Property<int>("ReportesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ContratosId");

                    b.Property<DateTime>("fecha_reportes");

                    b.Property<string>("nombre_reportes")
                        .IsRequired();

                    b.Property<string>("observacion")
                        .HasMaxLength(200);

                    b.HasKey("ReportesId");

                    b.HasIndex("ContratosId");

                    b.ToTable("Reportes");
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Usuarios", b =>
                {
                    b.Property<int>("UsuariosId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("contrasena")
                        .IsRequired();

                    b.Property<string>("correo")
                        .IsRequired();

                    b.Property<string>("usuario")
                        .IsRequired();

                    b.HasKey("UsuariosId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Auditorias", b =>
                {
                    b.HasOne("SISCO_SAYACv3._5.Models.Usuarios", "Usuarios")
                        .WithMany("Auditoria")
                        .HasForeignKey("UsuariosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Contratos", b =>
                {
                    b.HasOne("SISCO_SAYACv3._5.Models.Contratistas", "Contratistas")
                        .WithMany("Contrato")
                        .HasForeignKey("ContratistasId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Obras", b =>
                {
                    b.HasOne("SISCO_SAYACv3._5.Models.Contratistas", "Contratistas")
                        .WithMany("Obra")
                        .HasForeignKey("ContratistasId")
                        .HasConstraintName("ForeignKey_Obras_Contratistas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SISCO_SAYACv3._5.Models.Contratos", "Contratos")
                        .WithOne("Obras")
                        .HasForeignKey("SISCO_SAYACv3._5.Models.Obras", "ContratosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SISCO_SAYACv3._5.Models.Reportes", b =>
                {
                    b.HasOne("SISCO_SAYACv3._5.Models.Contratos", "Contratos")
                        .WithMany("Reporte")
                        .HasForeignKey("ContratosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
